name: "security"

permissions:
  actions: read
  contents: read
  security-events: write

on:
  workflow_dispatch:

  schedule:
    # Run every 24 hours Monday-Friday.
    - cron: "0 0 * * 1-5"

# Cancel in-progress runs for pull requests when developers push
# additional changes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-security
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  codeql:
    runs-on: tsw
    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go, javascript

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "~1.20"

      - name: Go Cache Paths
        id: go-cache-paths
        run: |
          echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - name: Go Mod Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-release-go-mod-${{ hashFiles('**/go.sum') }}

      # Workaround to prevent CodeQL from building the dashboard.
      - name: Remove Makefile
        run: |
          rm Makefile

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Send Slack notification on failure
        if: ${{ failure() }}
        run: |
          msg="❌ CodeQL Failed\n\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl \
            -qfsSL \
            -X POST \
            --data "${msg@Q}" \
            "${{ secrets.SLACK_SECURITY_FAILURE_WEBHOOK_URL }}"

  # We share a job because trivy and xray rely on the same Docker image.
  trivy_xray:
    runs-on: tsw
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: "~1.20"

      - name: Install sqlc
        run: |
          curl -sSL https://github.com/kyleconroy/sqlc/releases/download/v1.17.2/sqlc_1.17.2_linux_amd64.tar.gz | sudo tar -C /usr/bin -xz sqlc
      - name: Install yq
        run: go run github.com/mikefarah/yq/v4@v4.30.6
      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
      - name: Install protoc-gen-go-drpc
        run: go install storj.io/drpc/cmd/protoc-gen-go-drpc@v0.0.26
      - name: Install Protoc
        run: |
          # protoc must be in lockstep with our dogfood Dockerfile or the
          # version in the comments will differ. This is also defined in
          # ci.yaml.
          set -x
          cd dogfood
          DOCKER_BUILDKIT=1 docker build . --target proto -t protoc
          mkdir -p bin
          docker run --rm --entrypoint cat protoc /tmp/bin/protoc > ./bin/protoc
          chmod +x ./bin/protoc
          echo "./bin" >> $GITHUB_PATH

      - name: Build Coder linux amd64 Docker image
        id: build
        run: |
          set -euo pipefail

          version="$(./scripts/version.sh)"
          image_job="build/coder_${version}_linux_amd64.tag"

          # This environment variable force make to not build packages and
          # archives (which the Docker image depends on due to technical reasons
          # related to concurrent FS writes).
          export DOCKER_IMAGE_NO_PREREQUISITES=true
          # This environment variables forces scripts/build_docker.sh to build
          # the base image tag locally instead of using the cached version from
          # the registry.
          export CODER_IMAGE_BUILD_BASE_TAG="$(CODER_IMAGE_BASE=coder-base ./scripts/image_tag.sh --version "$version")"

          make -j "$image_job"
          echo "image=$(cat "$image_job")" >> $GITHUB_OUTPUT
      - name: Setup JFrog
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://cdr.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - name: Run JFrog xray
        run: |
          jf docker scan \
            ${{ steps.build.outputs.image }} | \
            tee xray.out
          if grep -q High xray.out; then
            exit 1
            curl \
              -qfsSL \
              -X POST \
              --data "JFrog Xray detected >=High vulnerabilities" \
              "${{ secrets.SLACK_SECURITY_FAILURE_WEBHOOK_URL }}"
          fi
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@e5f43133f6e8736992c9f3c1b3296e24b37e17f2
        with:
          image-ref: ${{ steps.build.outputs.image }}
          format: sarif
          output: trivy.sarif
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy.sarif
          category: "Trivy"

      - name: Upload Trivy scan results as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy
          path: trivy.sarif
          retention-days: 7

      - name: Send Slack notification on failure
        if: ${{ failure() }}
        run: |
          msg="❌ CodeQL Failed\n\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl \
            -qfsSL \
            -X POST \
            --data "${msg@Q}" \
            "${{ secrets.SLACK_SECURITY_FAILURE_WEBHOOK_URL }}"
  advisory-report:
    needs: [codeql, trivy_xray]
    runs-on: ubuntu-latest
    steps:
      - run: |
          reports=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          '/repos/coder/coder/code-scanning/alerts?state=open')
          num_reports=$(jq length <<< reports)
          if [[ $num_reports == 0 ]]; then
            echo "No reports found"
            exit 0
          fi
          echo "Found $num_reports reports"
          msg="There are $num_reports open security reports."
          curl \
            -qfsSL \
            -X POST \
            --data ${msg@Q} \
            "${{ secrets.SLACK_SECURITY_FAILURE_WEBHOOK_URL }}"
        env:
          GH_TOKEN: ${{ github.token }}

